name: Publish

on: push
  # release:
  #   types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          registry-url: https://npm.pkg.github.com/
          node-version: 14.x
          scope: '@radiantsgg'

      - name: Install dependancies
        run: |
          npm install

      - name: Fetch openapi.json
        run: |
          curl https://valorant.api.radiants.gg/v1/api-json --output openapi.json

      - name: Generate definition
        run: |
          npm run generate

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

